webtalk_init -webtalk_dir C:/Users/jimar/Desktop/digital lab/lab 2/Lab 2/Lab 2.sim/sim_1/synth/func/xsim/xsim.dir/testbench_func_synth/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Wed Nov 23 14:24:11 2022" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.3 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2405991" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "05561f99-7ef2-4127-ae2a-9d874c66c81d" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "4a833a90ecd649c283da467cdc9976f7" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "32" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "AMD Ryzen 5 5600X 6-Core Processor             " -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3700 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "2" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "34.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "3023 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "1" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "2.02_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "14976_KB" -context "xsim\\usage"
webtalk_transmit -clientid 4004577497 -regid "" -xml C:/Users/jimar/Desktop/digital lab/lab 2/Lab 2/Lab 2.sim/sim_1/synth/func/xsim/xsim.dir/testbench_func_synth/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/jimar/Desktop/digital lab/lab 2/Lab 2/Lab 2.sim/sim_1/synth/func/xsim/xsim.dir/testbench_func_synth/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/jimar/Desktop/digital lab/lab 2/Lab 2/Lab 2.sim/sim_1/synth/func/xsim/xsim.dir/testbench_func_synth/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
